config/routes.rb
Rails.application.routes.draw do

  # get 'assigments/new'
  # get 'assigments/create'
  # get 'assigments/edit'
  # get 'assigments/index'
  # get 'assigments/update'
  # get 'assigments/destroy'
  # get 'subjects/new'
  # get 'subjects/create'
  devise_for :users
  root to: 'pages#home'

  # resources :users do
  #   # resources :locations
  #   # resources :tags

  # end

  resources :contacts do
    resources :milestones
  end
  resources :locations
  resources :subjects
  resources :tags
  resources :assigments


  # resources :users do
  #   resources :locations, only: [:index, :show, :new, :create, :edit, :update]
  # end

  # resources :users do
  #   resources :tags, only: [:index, :show, :new, :create, :edit, :update]
  # end

  # resources :contacts do
  #   resources :milestones
  # end

  # resources :milestones do
  #   resources :locations, except: :destroy
  # end
 # require "sidekiq/web"
 #  authenticate :user, lambda { |u| u.admin } do
 #    mount Sidekiq::Web => '/sidekiq'
 #  end

end

app/models/milestone.rb
class Milestone < ApplicationRecord
  belongs_to :contact
  belongs_to :location
  has_many :subjects, dependent: :destroy
  has_many :tags , through: :subjects
  has_many :assigments

  accepts_nested_attributes_for :subjects, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contact, reject_if: :all_blank
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
before_action :find_milestone, only: [:show, :update, :destroy, :edit]
before_action :find_contact

  def index
    @milestones = Milestone.where(contact_id: find_contact.id ).order("created_at DESC")
    @contact = find_contact
    @locations = Location.all
    @assigments = Assigment.all
  end

  def new
    @milestone = Milestone.new
    @user = current_user
    @location = Location.new
    @subject = Subject.new
    @tag = Tag.new
  end


  def create
    @milestone = Milestone.new(milestone_params)
    @milestone.contact = @contact

      flash[:success] = "Your milestone has been set!"
      @locations = Location.all
      @have_location = false
      if not @milestone.last_location.blank?
          @locations.each do |l|
            if l.title == @milestone.last_location
              @milestone.location= l
              @have_location = true
              @milestone.save!
            end
          end
          if @have_location == false
            @location = Location.new(title:@milestone.last_location, user_id:@contact.user_id)
            if @location.save!
              @milestone.location = @location
              @milestone.save!
            end
          end
      end
    if @milestone.save!
      @tags = Tag.all

    if not @milestone.last_tag.blank?
      @have_first_tag = false
      if @milestone.last_tag != "Choose_tag"
        @tags.each do |t|
          if t.title == @milestone.last_tag
            @subject1 = Subject.new(milestone_id:@milestone.id, tag_id:t.id)
            @have_first_tag = true
            @subject1.save!
          end
        end
        if @have_first_tag == false
          @tag1 = Tag.new(title:@milestone.last_tag, user_id:@contact.user_id)
          @tag1.save!
          @subject1 = Subject.new(milestone_id:@milestone.id, tag_id:@tag1.id)
          @subject1.save!
        end
      end
    end

    # binding.pry
    if not @milestone.last_tag_two.blank?
      @have_second_tag = false
      if @milestone.last_tag_two != "Choose_tag"
        @tags.each do |t|
          if t.title == @milestone.last_tag_two
            @subject2 = Subject.new(milestone_id:@milestone.id, tag_id:t.id)
            @have_second_tag = true
            @subject2.save!
          end
        end
        if @have_second_tag == false
          @tag2 = Tag.new(title:@milestone.last_tag_two, user_id:@contact.user_id)
          @tag2.save!
          @subject2 = Subject.new(milestone_id:@milestone.id, tag_id:@tag2.id)
          @subject2.save!
        end
      end
    end
    assignment1_exist = false
    if not @milestone.assigment_one.empty?
      @milestone.assigments.each do |assignment|
        if assignment == milestone.assigment_one
          assignment1_exist = true
        end
      end
      if assignment1_exist == false
        @assigment1 = Assigment.new(milestone_id:@milestone.id, title:@milestone.assigment_one)
        @assigment1.save!
      end
    end

    assignment2_exist = false
    if not @milestone.assigment_two.empty?
      @milestone.assigments.each do |assignment|
        if assignment == milestone.assigment_two
          assignment2_exist = true
        end
      end
      if assignment2_exist == false
        @assigment2 = Assigment.new(milestone_id:@milestone.id, title:@milestone.assigment_two)
        @assigment2.save!
      end
    end

    redirect_to contact_milestones_path(@contact)
    else
      render :edit
    end
  end


  def edit
    @user = current_user
  end

    def update
      @milestone.update(milestone_params)
        flash[:success] = "Your milestone has been set!"
        @locations = Location.all
        if not @milestone.last_location.blank?
            if @milestone.last_location != @milestone.location.title
              @have_location = false
              @locations.each do |l|
                if l.title == @milestone.last_location
                  @milestone.location = l
                  @have_location = true
                  @milestone.save!
                end
              end
              if @have_location == false
                @location = Location.new(title:@milestone.last_location, user_id:@contact.user_id)
                if @location.save!
                  @milestone.location = @location
                  @milestone.save!
                end
              end
            end
        end
      @milestones = Milestone.all
      if @milestone.save!
        @subject1 = @milestone.subjects[0]
        @subject2 = @milestone.subjects[1]
        @subjects = Subject.all
        @tags = Tag.all

      if not @milestone.last_tag.blank?
        @first_tag_exist = false
        @has_first_tag = false
        if @milestone.last_tag != "Choose_tag"
          @tags.each do |t|
            if t.title == @milestone.last_tag
              @first_tag_exist = true
              @tag_id1 = t.id
              @milestone.tags.each do |mt|
                if mt.title == @milestone.last_tag
                  @has_first_tag = true
                end
              end
            end
          end
          if (@first_tag_exist == true && @has_first_tag == false)
            @new_subject1 = Subject.new(milestone_id:@milestone.id, tag_id:@tag_id1)
            @new_subject1.save!
            @milestone.subjects[0].destroy
          end
          if @first_tag_exist == false
            @tag1 = Tag.new(title:@milestone.last_tag, user_id:@contact.user_id)
            @tag1.save!
            @new_subject1 = Subject.new(milestone_id:@milestone.id, tag_id:@tag1.id)
            @new_subject1.save!
            if not @milestone.subjects[0].empty?
              @milestone.subjects[0].destroy
            end
          end
        end
      end

      if not @milestone.last_tag_two.blank?
        @seconed_tag_exist = false
        @has_second_tag = false
        if @milestone.last_tag_two != "Choose_tag"
          @tags.each do |t|
            if t.title == @milestone.last_tag_two
              @seconed_tag_exist = true
              @tag_id2 = t.id
              @milestone.tags.each do |mt|
                if mt.title == @milestone.last_tag_two
                  @has_second_tag = true
                end
              end
            end
          end
          if (@seconed_tag_exist == true && @has_second_tag == false)
            @new_subject2 = Subject.new(milestone_id:@milestone.id, tag_id:@tag_id2)
            @new_subject2.save!
            if !@milestone.subjects.nil?
              @milestone.subjects[1].destroy
            end
          end
          if @seconed_tag_exist == false
            @tag2 = Tag.new(title:@milestone.last_tag_two, user_id:@contact.user_id)
            @tag2.save!
            @new_subject2 = Subject.new(milestone_id:@milestone.id, tag_id:@tag2.id)
            @new_subject2.save!
            if not @milestone.subjects[1].empty?
              @milestone.subjects[1].destroy
            end
          end
        end
      end

      if not @milestone.assigment_one.empty?
        @assigment1 = Assigment.new(milestone_id:@milestone.id, title:@milestone.assigment_one)
        @assigment1.save!
      end

      if not @milestone.assigment_two.empty?
        @assigment2 = Assigment.new(milestone_id:@milestone.id, title:@milestone.assigment_two)
        @assigment2.save!
      end

        flash[:success] = " Your Milestone has been updated!"
        redirect_to contact_milestones_path(@contact, @milestone)
      else
        render :edit
      end
    end

  def destroy
    @milestone.destroy
    redirect_to contact_milestones_path(@contact)
    flash[:success] = "Your Milestone has been deleted!"
  end

  def show
  end

  private

  def find_contact
    @contact = Contact.find(params[:contact_id])
  end

  def find_milestone
   @milestone = Milestone.find(params[:id])
  end

  def milestone_params
    params.require(:milestone).permit(:note, :last_location, :last_tag_two, :last_tag, :contact_type, :assigment_one, :assigment_two, :location_id)
    # subjects_attributes: [:id, :_destroy, :tag_id, tag_attributes: [:id, :_destroy, :title]]
    # location_attributes: [:id, :_destroy, :title]
    # contact_attributes: [:id, :first_name, :last_name, :position, :company, :username, :email, :phone_number]
    # )
  end

  def assigment_params
    params.require(:assigment).permit(:title, :milestone_id, :completed)
  end

end

app/views/milestones/_form.html.erb
<div class="text-center wrapper-form">
  <div class="form-row col-sm-offset-4">
    <div class ="form-title" ><%= 'Milestone Details' %></div>
    <div class = "mandatory" ><%='*Mandatory fields'%></div>
    <div class="contact-form col-sm-4">
     <%= simple_form_for @milestone, url: contact_milestones_path do |f| %>
    <!-- <div class="logo-container">
            <%#= link_to root_path, class: "navbar-wagon-brand logo-reg" do %>
    <%#= image_tag "rememberme.png", height: 50 %>
            <%# end %>
    </div> -->

    <!-- <form class="details">
        <div class="input-container">
          <div class="input-container"> -->
      <div class=" col-md-6">
      <% @types = ['Physical meeting' , 'Virtual (Email etc)', 'Phone call'] %>
      <%= f.input :contact_type, collection: @types , label: false, placeholder: 'Physical meeting/Virtual/Phone', include_blank: false, prompt:'Choose contact point*' %>
      </div>

      <div class="dropdown-text col-md-6">
        <% @locations_array = [] %>
        <% @user.locations.each do  |l| %>
          <% @locations_array << l.title %>
        <%end%>
        <% @locations_array.uniq! %>
       <select name="milestone_form_location" id="milestone_form_location">
        <option value="Choose_location">Choose a location*</option>
         <option value="milestone_fake_location">Enter new location</option>
         <% @locations_array.each do |la|%>
         <option value='<%=la%>'><%=la%></option>
         <% end %>
       </select>
      <%= f.input :last_location, label: 'Location:', placeholder: 'Type new location', input_html: { id: 'milestone_location_dropdown'}, label: false  %>
       </div>

      <div class="dropdown-text col-md-6">
        <% @tags_array = [] %>
        <% @user.tags.each do  |t| %>
          <% @tags_array << t.title %>
        <%end%>
        <% @tags_array.uniq! %>
       <select name="milestone_form_tag1" id="milestone_form_tag1">
        <option value="Choose_tag">Add a tag?</option>
         <option value="milestone_fake_tag1">Create a  new tag</option>
         <% @tags_array.each do |ta|%>
         <option value='<%=ta%>'><%=ta%></option>
         <% end %>
       </select>
      <%= f.input :last_tag, label: 'Tag:', placeholder: 'Type new tag', input_html: { id: 'milestone_tag1_dropdown'}, label: false  %>
      </div>


      <div class="dropdown-text col-md-6">
       <select name="milestone_form_tag2" id="milestone_form_tag2">
        <option value="Choose_tag">Add a tag?</option>
         <option value="milestone_fake_tag2">Create a  new tag</option>
         <% @tags_array.each do |ta|%>
         <option value='<%=ta%>'><%=ta%></option>
         <% end %>
       </select>
      <%= f.input :last_tag_two, label: 'Tag:', placeholder: 'Type new tag', input_html: { id: 'milestone_tag2_dropdown'}, label: false  %>
      </div>

       <div class="dropdown-text col-md-12">
          <%= f.input :note, label: false, placeholder: 'How can I help my contact?',class: "col-sm-5 username-input with-placeholder", id: "username" %>
        </div>

        <div class=" col-md-6 ">
      <%= f.input :assigment_one, label: false, placeholder: 'To do' %>
      </div>
      <div class=" col-md-6 ">
      <%= f.input :assigment_two, label: false, placeholder: 'To do' %>
      </div>

        <%= f.submit 'Submit contact', class: 'hidden', id: 'submit_button' %>
       <% end %>
     </div>
           <div class="newbutton" id="newbutton" >Submit milestone</div>
   </div>
</div>

app/views/milestones/create.html.erb
<h1>Milestones#create</h1>
<p>Find me in app/views/milestones/create.html.erb</p>

app/views/milestones/destroy.html.erb
<h1>Milestones#destroy</h1>
<p>Find me in app/views/milestones/destroy.html.erb</p>

app/views/milestones/edit.html.erb
<div class="text-center wrapper-form">
  <div class="form-row col-sm-offset-4">
     <div class ="form-title" ><%= 'Milestone Details' %></div>
     <div class = "mandatory" ><%='*Mandatory fields'%></div>
    <div class="contact-form col-sm-4">
      <%= simple_form_for @milestone, url: contact_milestone_path do |f| %>

      <div class=" col-md-6">
      <% @types = ['Physical meeting' , 'Virtual (Email etc)', 'Phone call'] %>
      <%= f.input :contact_type, collection: @types , label: false, placeholder: 'Physical meeting/Virtual/Phone', include_blank: false, prompt:'Choose contact point*' %>
      </div>

      <div class="dropdown-text col-md-6">
        <% location_array = @user.locations.map {|l| l.title} %>
       <select name="milestone_form_location" id="milestone_form_location">
        <option value="Choose_location">Choose a location*</option>
         <option value="milestone_fake_location"><strong>Create a new location<strong></option>
         <% location_array.each do |la|%>
         <option value='<%=la%>'><%=la%></option>
         <% end %>
       </select>
      <%= f.input :last_location, label: 'Location:', placeholder: 'Type new location', input_html: { id: 'milestone_location_dropdown'}, label: false  %>
       </div>

      <div class="dropdown-text col-md-6">
      <% tags_array = @user.tags.map {|t| t.title} %>
       <select name="milestone_form_tag1" id="milestone_form_tag1">
        <option value="Choose-tag">Upadate the tag?</option>
         <option value="milestone_fake_tag1"><strong>Create a new tag<strong></option>
         <% tags_array.each do |ta|%>
         <option value='<%=ta%>'><%=ta%></option>
         <% end %>
       </select>
      <%= f.input :last_tag, label: 'Tag:', placeholder: 'Type new tag', input_html: { id: 'milestone_tag1_dropdown'}, label: false  %>
      </div>


      <div class="dropdown-text col-md-6">
      <% tags_array = @user.tags.map {|t| t.title} %>
       <select name="milestone_form_tag2" id="milestone_form_tag2">
        <option value="Choose-tag">Upadate the tag?</option>
         <option value="milestone_fake_tag2"><strong>Create a new tag<strong></option>
         <% tags_array.each do |ta|%>
         <option value='<%=ta%>'><%=ta%></option>
         <% end %>
       </select>
      <%= f.input :last_tag_two, label: 'Tag:', placeholder: 'Type new tag', input_html: { id: 'milestone_tag2_dropdown'}, label: false  %>
      </div>

       <div class="dropdown-text col-md-12">
          <%= f.input :note, label: false, placeholder: 'How can I help my contact?',class: "col-sm-5 username-input with-placeholder", id: "username" %>
        </div>

        <div class=" col-md-6 ">
      <%= f.input :assigment_one, label: false, placeholder: 'To do' %>
      </div>
      <div class=" col-md-6 ">
      <%= f.input :assigment_two, label: false, placeholder: 'To do' %>
      </div>


       <%= f.submit 'Submit contact', class: 'hidden', id: 'submit_button' %>
       <% end %>
           <div class="newbutton btn" id="newbutton" >Submit contact</div>
      </div>
    </div>
  </div>

app/views/milestones/index.html.erb
<% phy = 0 %>
<% virt = 0 %>
<% pho = 0 %>
<% @milestones.each do |milestone| %>
<% if  milestone.contact_type == "Phone call"%>
<% pho += 1 %>
<% end %>
<% if milestone.contact_type == "Physical meeting"%>
<% phy += 1 %>
<% end %>
<% if  milestone.contact_type == "Virtual (Email etc)"%>
<% virt += 1 %>
<% end %>
<% end %>
<div class="container-fluid intro-wrapper">

  <div class="container">
    <div class="row ">
      <!-- Chart -->
      <div class="col-md-4 col-sm-12 align-center">
        <div class="ct-chart">
          <script class="chart">
            var milestoneChartData = {
              labels: [' ', ' ', ' '],
              label: "Population (millions)",
              backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f"],
              series: [<%= phy %>, <%= virt %> , <%= pho %> ]
            };
          </script>
        </div>

        <div class="chart-info align-center">
          <div id="labels">
            <ul>
              <li><span></span>Physical</li>
              <li><span></span>Virtual</li>
              <li><span></span>Phone</li>
            </ul>
          </div>
        </div>

        <div class="milestones-counter chart-info">
          <% counter = 0 %>
          <% @milestones.each do |stone| %>
          <% counter += 1 %>
          <% end %>
          <h5>You and <%= @contact.first_name.capitalize %> have <%= counter %> milestones</h5>
          <h5>Last milestone: <strong><%= @milestones.first.created_at.strftime "%B %e %G" %></strong></h5>
        </div>
      </div>
      <!-- Middle Column Info -->
      <div class="col-md-4 col-sm-12 align-center">
        <div class="row  text-xs-center">
          <div class="contact-info-dash">
            <div class="dash-first-info">
              <div class="contact-name-dash contacts-inf" >
                <h2><strong><%= @contact.first_name.capitalize %> <%= @contact.last_name.capitalize %></strong></h2>
              </div>
              <div class="contact-email-dash contacts-inf">
                <% unless @contact.email.empty? %>
                <div><h5><i class="far fa-envelope"></i> <%= @contact.email %></h5></div>
                <% end %>
              </div>
              <div class="contact-phone-dash contacts-inf">
                <% unless @contact.phone_number.empty? %>
                  <div><h5><i class="fas fa-mobile-alt"></i> <%= @contact.phone_number %></h5></div>
                <% end %>
              </div>
              <div class="position-c contacts-inf">
                <% unless  @contact.position.empty? && @contact.company.empty? %>
                  <div><%= @contact.position.upcase %> at <strong><%= @contact.company.capitalize%></strong></div>
                <% end %>
              </div>
              <div class="linkedin-dash contacts-inf">
                <% unless  @contact.username.empty? %>
                  <div><h5><i class="fab fa-linkedin" style="color: #096ab6;"></i> Username: <%= @contact.username %></h5></div>
                <% end %>
              </div>
              <div class="birth-date-dash contacts-inf">
                <% unless  @contact.date_of_birth.nil? %>
                  <h5>Date of birth: <%= @contact.date_of_birth %></h5>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row buttons-row">
          <div class="m-buttons contacts-inf">
            <%= link_to "New Milestone", new_contact_milestone_path(@contact), class: "btn-medium mile-button" %>
            <%= link_to "Edit Contact", edit_contact_path(@contact.id), class: "btn-medium mile-button" %>
          </div>
        </div>     
      </div>
      <!-- Right Column... Tags -->
      <div class="col-md-4 col-sm-12">
        <div class="locat-tag-dash">
              <div class="mile-tag">
                <i class="fas fa-tags " style="color: black;"></i>
                <p class="milestone-tags">
                  <% @contact.tags.each do |tag| %>
                  <p class="badge-tag badge dash-icons"><%= tag.title %></p>
                  <% end %>
                </p>
              </div>
            </div>
              <div class="locat dashboard-scroll">
                <i class="fas fa-globe globe dash-icons" style="color: black;"></i>
                <br>
                <% @contact.locations.each do |location| %>
                <p class="loca"><%= location.title %></p>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
      <!-- 2nd ROW -->
       <div class="row">
        <div class="col-sm-12">
        <div class="m-buttons text-center contacts-inf">
         <%= link_to "New Milestone", new_contact_milestone_path(@contact), class: "btn-medium mile-button first-button" %>
         <%= link_to "Edit Contact", edit_contact_path(@contact.id), class: "btn-medium mile-button second-button" %>
        </div>
      </div>
      </div>
      <div class="intro-milestone"></div>
    </div>
    </div>
  </div>
</div>



<section class="timeline">
  <ul>

    <% @milestones.each do |milestone| %>
    <li>
      <div class="stone">
        <div>
          <%= link_to edit_contact_milestone_path(@contact, milestone) do %>
          <i class="fas fa-edit milestone-edit text-center" style="color: black;"></i>
          <% end %>
        </div>

        <div>
          <time style="font-size: 18px"  class="text-center"><%= milestone.created_at.strftime "%B %e %G" %></time>
        </div>
        <div class="locat-tag">
          <div class="mile-tag text-center">
            <i class="fas fa-tags " style="color: black;"></i>
            <p class="milestone-tags">
              <% milestone.tags.each do |tag| %>
              <p class="badge-tag badge"><%= tag.title %></p>
              <% end %>
            </p>
          </div>
          <div class="locat text-center">
            <i class="fas fa-globe globe" style="color: black;"></i>
            <br>
            <p style="font-size: 17px;" class=" loca"><%= milestone.location.title %></p>
          </div>
        </div>
        <% unless milestone.note.empty? %>
          <h5  style="color: #2e242c;, font-weight: bold;">How can I help my contact?</h5>
          <div class="mile-note">
            <h5 style="color: gray;"><%= milestone.note %></h5>
          </div>
        <% end %>
        <hr class="toq-line" size="pixels">

        <%= link_to contact_milestone_path(@contact, milestone),
        method: :delete,
        data: { confirm: "Are you sure?" }, class: 'link'  do %>
        <i class="fas fa-trash-alt delete-milestone"></i>
        <% end %>
      </h5>

      <div>
        <% unless milestone.assigments.empty? %>
        <h5 style="color: #2e242c;, font-weight: bold;">TO DO:</h5>
        <% end %>
        <% milestone.assigments.each do |assigment|%>
        <% unless assigment.title.nil? %>

          <p style="color: #ccc;"><%= assigment.title %></p>

          <% end %>

          <% end %>
        </div>
      </div>

    </div>

  </li>
  <% end %>
</ul>
</section>

app/views/milestones/new.html.erb
<div class="wrapper-form">
  <%= render 'form' %>
</div>

app/views/milestones/show.html.erb
<h1>Milestones#show</h1>
<%= @milestone.contact_type %>
<%= @milestone.location.title %>
<% @milestone.tags.each do |t| %>
<%= t.title %>
<% end %>

app/views/milestones/update.html.erb
<h1>Milestones#update</h1>
<p>Find me in app/views/milestones/update.html.erb</p>