config/routes.rb
Rails.application.routes.draw do

  # get 'assigments/new'
  # get 'assigments/create'
  # get 'assigments/edit'
  # get 'assigments/index'
  # get 'assigments/update'
  # get 'assigments/destroy'
  # get 'subjects/new'
  # get 'subjects/create'
  devise_for :users
  root to: 'pages#home'

  # resources :users do
  #   # resources :locations
  #   # resources :tags

  # end

  resources :contacts do
    resources :milestones
  end
  resources :locations
  resources :subjects
  resources :tags
  resources :assigments


  # resources :users do
  #   resources :locations, only: [:index, :show, :new, :create, :edit, :update]
  # end

  # resources :users do
  #   resources :tags, only: [:index, :show, :new, :create, :edit, :update]
  # end

  # resources :contacts do
  #   resources :milestones
  # end

  # resources :milestones do
  #   resources :locations, except: :destroy
  # end
 # require "sidekiq/web"
 #  authenticate :user, lambda { |u| u.admin } do
 #    mount Sidekiq::Web => '/sidekiq'
 #  end

end

app/views/shared/_banner.html.erb
<% if user_signed_in? %>
  <div class="banner banner-signed-in" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.5) 0%, rgba(0,36,61,0.5) 50%), url(<%= image_path 'networking.jpg'%>);">
    <div class="banner-content">
      <div class="banner-info">
        <h1>Forget Me Not</h1>
        <p>Remember the people you met.</p>
      </div>
      <div class="search-button">
        <%= link_to 'Create a Contact!', new_contact_path, method: :get, class: "btn btn-info btn-lg" %>
      </div>
      <div class="name-search">
        <i class="fas fa-search"></i>
        <%= form_tag contacts_path, method: :get  do %>
            <%= text_field_tag :query, params[:query], type: "search", size: "15", class: "form-control search-input-home", 
            placeholder: "Find a contact by name", onsearch: "toggleDisplay()" %>
          <%  end %>
        <script>
          function toggleDisplay(){
            var button = document.getElementById('location');
            if (button.style.display === "block"){
              button.style.display = "none";
            }else{
              button.style.display = "block";    
            }
          }
        </script>
      </div>
    </div>
  </div>
<% else %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'world.jpg' %>);">
    <div class="banner-content">
      <h1>Forget Me Not</h1>
      <p>
        <span id="banner-typed-text"></span>
      </p>
      <div class="button-banner">
        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-info btn-lg", method: :get %>
      </div>
      <div class="button-banner home-login">
        <%= link_to 'Log In', new_user_session_path, class: "btn btn-info", method: :get %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
     <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <a class="card-link" href="#" ></a>
</div>
    </div>
    <div class="col-xs-12 col-sm-4">
     <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <a class="card-link" href="#" ></a>
</div>
    </div>
    <div class="col-xs-12 col-sm-4">
     <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <a class="card-link" href="#" ></a>
</div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>


  

app/views/shared/_location_cards.html.erb
<% @contacts_for_location.each do |contact|  %>
  <div class="col-md-4">  
    <div class="phone-container hover-shadow"> 
      <div class="contact-go-timeline">
        <%=link_to new_contact_milestone_path(contact) do %> 
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
      <%= link_to contact_milestones_path(contact), class: "phone-link" do %>
        <div class="contact-info">
          <div class="contact-name">
            <%= contact.first_name.upcase + " " + contact.last_name.upcase %>
          </div>
          <div class="contact-email">
            <%= contact.email %>
          </div>
        </div>
        <div class="associations">
          <div class="tags">
            <p><i class="fas fa-tags"></i></p>
            <% tags_array = [] %>
            <% contact.tags.each do |tag| %>
              <% tags_array << tag.title %>
            <% end %>
            <% tags_array.uniq! %>
            <% tags_array.each do |tag| %>
              <p class="badge badge-danger badge-sm badge-tag"><%= tag %></p>
            <% end %>        
          </div>
          <div class="locations">
            <p><i class="fas fa-globe"></i></p>
            <% locations_array = [] %>
            <% contact.locations.each do |location| %>
              <% locations_array   << location.title %>
            <%end%>
            <% locations_array.uniq!  %>
            <% locations_array.each do |location| %>  
              <p class="badge  badge-danger location-badge"><%= location %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_milestone_cards.html.erb
<% @new_milestones.each do |milestone|  %>
  <div class="col-md-4">  
    <%= link_to contact_milestones_path(milestone.contact), class: 'phone-link' do  %>
      <div class="milestone-container hover-shadow">    
        <div class="milestone-info">
          <div class="milestone-title">
          <%= milestone.contact.first_name.capitalize + " " + milestone.contact.last_name.capitalize %>
          </div>          
            <%=  milestone.location.title.upcase %>
          <div class="contact-email">
            <%= milestone.contact.email %>
          </div>
          <div class="milestone-date">
            <%= milestone.updated_at.strftime('%d %b %Y') %>
          </div>
        </div>              
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "rememberme.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add Contact", new_contact_path , class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "bryan.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
    <% if user_signed_in? %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to "Add Contact", new_contact_path , class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li> 
            <%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out"></i>
            <%= t(".sign_out", default: "Log out") %>
          </li>
           <% end %>
      </ul>
    </div>
  </div>
  <% else %>
   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to "Add Contact", new_user_session_path , class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li> <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_phone_cards.html.erb
<% @contacts.each do |contact|  %>
  <div class="col-md-4">  
    <div class="phone-container hover-shadow"> 
      <div class="contact-go-timeline">
        <%=link_to new_contact_milestone_path(contact) do %> 
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
      <%= link_to contact_milestones_path(contact), class: "phone-link" do %>
        <div class="contact-info">
          <div class="contact-name">
            <%= contact.first_name.upcase + " " + contact.last_name.upcase %>
          </div>
          <div class="contact-email">
            <%= contact.email %>
          </div>
        </div>
        <div class="associations">
          <div class="tags">
            <p><i class="fas fa-tags"></i></p>
            <% tags_array = [] %>
            <% contact.tags.each do |tag| %>
              <% tags_array << tag.title %>
            <% end %>
            <% tags_array.uniq! %>
            <% tags_array.each do |tag| %>
              <p class="badge badge-danger badge-sm badge-tag"><%= tag %></p>
            <% end %>        
          </div>
          <div class="locations">
            <p><i class="fas fa-globe"></i></p>
            <% locations_array = [] %>
            <% contact.locations.each do |location| %>
              <% locations_array   << location.title %>
            <%end%>
            <% locations_array.uniq!  %>
            <% locations_array.each do |location| %>  
              <p class="badge  badge-danger location-badge"><%= location %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_search_home.html.erb
<% if user_signed_in? %>
	<div class="container-fluid home-wrap">
    <div class="container gradiant-background-home">
      <div class=" row home-row-searches">
        <h4 class="text-center"><strong>Search by Tag or Location</strong></h4>
        <div class="col-md-6 location-column">
          <div class="location-search text-center ">
            <%= button_tag 'Location', class: "btn btn-info", onclick: "buttonDisappear()" %>
          <div id="location" style="display: none;">
            <script>
              function buttonDisappear(){
                var button = document.getElementById('location');
                if (button.style.display === "none"){
                  button.style.display = "block";
                } else {
                  button.style.display = "none";
                }
              }
            </script>
              <% @my_locations.each do |location|  %>
                  <%= link_to location.title, contacts_path(location_id: location.id), onclick: "showLocation()", class: "badge badge-danger location-badge hover-shadow"  %>
              <%  end  %>
            </div>
            <script>
              function showLocation(){
                var button = document.getElementById('contact-location');
                if (button.style.display === "block"){
                  button.style.display = "none";
                } else {
                  button.style.display = "block";
                }
              }
            </script>
          </div>
        </div>
        <div class="col-md-6 tag-column">
          <div class="tag-search text-center">
            <%= button_tag'Tags', class: "tags-search btn btn-info", onclick: "toggleFunction()"  %>
            <script>
              function toggleFunction(){
                var button = document.getElementById('tags');
                if (button.style.display === "none"){
                  button.style.display = "block";
                } else {
                  button.style.display = "none";
                }
              }
            </script>
          </div>
          <div id="tags" class="text-center" style="display: none;">
            <% @tag_names.each do |tag|  %>
                <%= link_to tag.title, contacts_path(tag_id: tag.id), onclick:"showTags()", class: "badge badge-danger badge-sm badge-tag hover-shadow" %>
            <% end %>
            <script>
              function showTags(){
                var button = document.getElementById('tags-contacts');
                if (button.style.display === "block"){
                  button.style.display = "none";
                } else {
                  button.style.display = "block";
                }
              }
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="container-fluid most-relevant">
  <div class="container relevants">
    <h4 class="text-center"><strong>Your Most Recent Milestones</strong></h4>
    <div class="row">
      <%= render "shared/milestone_cards" %>
    </div>
  </div>
</div>
<% end %>
<% unless user_signed_in? %>
<div class="container-fluid home-wrap">
  <div class="container gradiant-background-home">
    <h4 class="text-center header-why-us"><strong>Why Use Forget Me Not?</strong></h4>
      <div class="row row-why-us">
        <div class="col-xs-12 col-sm-3 text-center">
          <%= image_tag('networking (1).svg', size: "100") %>
          <h5 class="text-why-us">Master networking</h5>
        </div>
        <div class="col-xs-12 col-sm-3 text-center">
          <%= image_tag('003-worker.svg', size: "100") %>
          <h5 class="text-why-us">Remember people</h5>
        </div>
        <div class="col-xs-12 col-sm-3 text-center">
          <%= image_tag('001-growth.svg', size: "100") %>
          <h5 class="text-why-us">Establish beneficial relationships</h5>
        </div>
        <div class="col-xs-12 col-sm-3 text-center">
          <%= image_tag('002-chat-bubble.svg', size: "100") %>
          <h5 class="text-why-us">Stay current</h5>
        </div>
      </div>
  </div>
</div>
<% end %>
<% if user_signed_in? %>
<div class="container-fluid home-wrap">
  <div class="container relevants">
    <h4 class="text-center header-why-us"><strong>How It Works</strong></h4>
    <div class="row-why-us text-center ">
      <div class="col-xs-12 col-sm-3">
        <%= image_tag('001-employee.svg', size: "100") %>
        <h5 class="text-how">Create Contacts</h5>
      </div>
      <div class="col-xs-12 col-sm-3">
        <%= image_tag('002-mountain.svg', size: "100") %>
        <h5 class="text-how">Add a milestone to a contact</h5>
      </div>
      <div class="col-xs-12 col-sm-3">
        <%= image_tag('003-clipboard.svg', size: "100") %>
        <h5 class="text-how">Manage Your Contacts</h5>
      </div>
      <div class="col-xs-12 col-sm-3">
        <%= image_tag('megaphone.svg', size: "100") %>
        <h5 class="text-how"> Get Alerts</h5>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="container-fluid most-relevant text-center">
  <div class="container about-us gradiant-background-home about-us-wrapper text-center">
    <h4 class="text-center"><strong>About Us</strong></h4>
    <div class="col-xs-12 col-sm-4 text-center">
      <div class="team-card text-center">
        <%= image_tag('ashraf.jpeg', size: "100", class: "about-us-photo")%>
        <p class="team-text">I completed one semester in FH Kaernten in Network engineering and I may continue.I will do my best to work on myself to be eligible to work as a web-developer and build the project that I want.</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 text-center">
      <div class="team-card text-center">
        <%= image_tag('bryan.jpeg', size: "100", class: "about-us-photo") %>
        <p class="team-text">I had studied International Relations at university and decided to work as an EMT for around two years. I plan to try to continue as a web developer and hopefully learn other languages and possibly go into game design!</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 text-center">
      <div class="team-card text-center">
        <%= image_tag('adi.jpeg', size:"100", class: "about-us-photo") %>
        <p class="team-text"> Worked at a Strategic consulting firm, leading a team in diverse projects. specializing in the finance world- banking, investment funds, insurance companies etc</p>
      </div>
    </div>   
  </div>
          <p>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></p>
</div>

app/views/shared/_tag_cards.html.erb
<% @list_of_contacts.each do |contact|  %>
  <div class="col-md-4">  
    <div class="phone-container hover-shadow"> 
      <div class="contact-go-timeline">
        <%=link_to new_contact_milestone_path(contact) do %> 
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
      <%= link_to contact_milestones_path(contact), class: "phone-link" do %>
        <div class="contact-info">
          <div class="contact-name">
            <%= contact.first_name.upcase + " " + contact.last_name.upcase %>
          </div>
          <div class="contact-email">
            <%= contact.email %>
          </div>
        </div>
        <div class="associations">
          <div class="tags">
            <p><i class="fas fa-tags"></i></p>
            <% tags_array = [] %>
            <% contact.tags.each do |tag| %>
              <% tags_array << tag.title %>
            <% end %>
            <% tags_array.uniq! %>
            <% tags_array.each do |tag| %>
              <p class="badge badge-danger badge-sm badge-tag"><%= tag %></p>
            <% end %>        
          </div>
          <div class="locations">
            <p><i class="fas fa-globe"></i></p>
            <% locations_array = [] %>
            <% contact.locations.each do |location| %>
              <% locations_array   << location.title %>
            <%end%>
            <% locations_array.uniq!  %>
            <% locations_array.each do |location| %>  
              <p class="badge  badge-danger location-badge"><%= location %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>